/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2018-09-02 10:26:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import user.model.vo.User;
import hsp.model.vo.*;
import java.util.*;
import user.model.vo.User;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/user/../../footer.jsp", Long.valueOf(1535623718000L));
    _jspx_dependants.put("/views/user/../.././views/support/accessTerms.jsp", Long.valueOf(1535623716000L));
    _jspx_dependants.put("/views/user/../.././views/support/policy.jsp", Long.valueOf(1535623716000L));
    _jspx_dependants.put("/views/user/../../header.jsp", Long.valueOf(1535623792000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("hsp.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("user.model.vo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	String loginuserid = (String)session.getAttribute("userId");
	User user = (User)request.getAttribute("profileuser");
    Host profileH = (Host)request.getAttribute("profileH");	
    SurferPartner profileS = (SurferPartner)request.getAttribute("profileS");
    SurferPartner profileP = (SurferPartner)request.getAttribute("profileP");
 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("   content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/hifive/resources/image/index/logo2.png\" />\r\n");
      out.write("<title>Traveler's Couch</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hifive/resources/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"  src=\"https://openapi.map.naver.com/openapi/v3/maps.js?clientId=it6Bx0b47tvhxxRDP2mg&submodules=geocoder\"></script>\r\n");
      out.write("<script src=\"/hifive/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("   /* 여기 이새끼가 전체 우리 컨테이너 역할 */\r\n");
      out.write("   .container{\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   padding: 10px;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   /* 이게  우리가 이제 만들어야할 공간 */\r\n");
      out.write("   #main{width:1000px;overflow:hidden;}\r\n");
      out.write("   /* 이게 왼쪽 창 float:left 가  다음 창을 붙여준다 */\r\n");
      out.write("   #menu{width:250px;margin:5px 0 0 0;float:left;}\r\n");
      out.write("   /* 이게 오른족 꾸미는거  */\r\n");
      out.write("   #content1{width:740px;margin:5px 0 0 0;float:left;padding:0 0 0 10px;}\r\n");
      out.write("   \r\n");
      out.write("   #card_info { text-align:center; }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar userid = '");
      out.print( user.getUser_Id() );
      out.write("';\r\n");
      out.write("\t\tvar loginuserid = '");
      out.print( loginuserid );
      out.write("';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 리뷰 \r\n");
      out.write("\t\t$.ajax({\t\r\n");
      out.write("\t  \t  url : \"/hifive/reviewlist\",\r\n");
      out.write("\t    \t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tdata : {uid : userid},\r\n");
      out.write("\t\t\t\tdataType : \"json\",\t\t\t\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t//배열로 된 전송값을 직렬화해서 하나의 문자열로 바꿈\r\n");
      out.write("\t\t\t\t\tvar jsonStr = JSON.stringify(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//문자열을 json 객체로 바꿈\r\n");
      out.write("\t\t\t\t\tvar json = JSON.parse(jsonStr);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar values = \"\";\r\n");
      out.write("\t\t\t\t\tif(json.list.length == 0){\r\n");
      out.write("\t\t\t\t\t\tvalues += \"<br><br><center>등록된 리뷰가 없습니다.</center>\";\r\n");
      out.write("\t\t\t\t\t\t$(\"#review\").html($(\"#review\").html()+values);\t\r\n");
      out.write("\t\t\t\t\t} else{\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfor(var i in json.list){\r\n");
      out.write("\t\t\t\t\t\t\tvalues += \"<div class='card'> <div class='card-body'>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<a href='/hifive/profileinfo?userid=\"+json.list[i].user_id+\"'><font style='font-size:13pt'><b>\" + json.list[i].user_id + \"</a>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"</b></font> <font style='font-size:10pt'> 님이 작성한 후기입니다. <br></font>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<font style='font-size:8pt'>(\" + json.list[i].review_date + \")</font><br>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<font style='font-size:14pt'>\" + json.list[i].content +\"</font></div></div>\";\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tif(json.list[i].user_id == loginuserid)\r\n");
      out.write("\t\t\t\t\t\t\t\tvalues += \"<a href='/hifive/reviewdelete?reviewno=\" + json.list[i].review_no \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"&uid=\" + userid + \"'>삭제</a><br><br>\";\r\n");
      out.write("\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t\tvalues += \"<br><br>\";\r\n");
      out.write("\t\t\t\t\t\t}\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#review\").html($(\"#review\").html()+values);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}, // success\r\n");
      out.write("\t\t\t\terror : function(jqXHR, textstatus, errorThrown){\r\n");
      out.write("\t\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textstatus + \", \" + errorThrown);\r\n");
      out.write("\t\t\t\t} // error\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 선호 버튼\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"/hifive/profilefavorite\",\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\tdata : {userid : userid},\r\n");
      out.write("\t\t\tdataType : \"json\",\t\t\t\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvalue =\"\";\r\n");
      out.write("\t\t\t\tif(data.result == 0){ // 내 아이디\r\n");
      out.write("\t\t\t\t\t//value = \"<input type='button' class='btn btn-warning' value='선호' style='width: 200px;' disabled>\";\r\n");
      out.write("\t\t\t\t} else if(data.result == 1){ // 상대방이 이미 favorite 등록되어있음\r\n");
      out.write("\t\t\t\t\tvalue += \"<input type='button' class='btn btn-warning' value='선호하는 유저 취소' style='width: 200px;' \" \r\n");
      out.write("\t\t\t\t\t+ \"onclick='location.href=\\\"/hifive/favoritedelete?f_userid=\" + userid + \"\\\"'>\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tvalue += \"<input type='button' class='btn btn-warning' value='선호하는 유저로 등록' style='width: 200px;' \" \r\n");
      out.write("\t\t\t\t\t+ \"onclick='location.href=\\\"/hifive/favoriteinsert?f_userid=\" + userid + \"\\\"'>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#favorite\").html($(\"#favorite\").html()+value);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}, // success\r\n");
      out.write("\t\t\terror : function(jqXHR, textstatus, errorThrown){\r\n");
      out.write("\t\t\t\tconsole.log(\"error : \" + jqXHR + \", \" + textstatus + \", \" + errorThrown);\r\n");
      out.write("\t\t\t} // error\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 리뷰 창 (다른 사람 프로필에서만 쓸 수 있음)\r\n");
      out.write("\t\tif(userid!=loginuserid){\r\n");
      out.write("\t\t\tvar value = \"<br><div class='card' style='width: auto;'><h6 class='card-header' id='card_info'>리뷰 작성하기</h6> \" \r\n");
      out.write("\t\t\t\t\t+ \"<div class='card-body' id='write_review' align='center'> \"\r\n");
      out.write("\t\t\t\t\t+ \"<form action='/hifive/reviewwrite?' method='post'> \"\r\n");
      out.write("\t\t\t\t\t+ \"<input type='hidden' name='uid' value=\" + userid + \"> \"\r\n");
      out.write("\t\t\t\t\t+ \"<textarea name='review' cols='80' rows='5'></textarea><br> \"\r\n");
      out.write("\t\t\t\t\t+ \"<input class='btn btn-outline-secondary' type='submit' value='작성'></form></div></div>\";\r\n");
      out.write("   \t\t\t$(\"#review_write\").html($(\"#review_write\").html()+value);\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar loginid = \"");
      out.print( loginuserid );
      out.write("\";\r\n");
      out.write("\tvar profileid = \"");
      out.print( user.getUser_Id() );
      out.write("\";\r\n");
      out.write("\tvar safety = \"");
      out.print( user.getSafety_check() );
      out.write("\"\r\n");
      out.write("\r\n");
      out.write("\tfunction hrequest() {\r\n");
      out.write("\t\tif(loginid == profileid) {\r\n");
      out.write("\t\t\talert(\"자신에게는 신청할 수 없습니다.\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tif(safety == 'N') {\r\n");
      out.write("\t\t\t\talert(\"안전 유의 사항을 체크해주세요.\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$.ajax({\t\r\n");
      out.write("\t\t\t\t  \turl : \"/hifive/request\",\r\n");
      out.write("\t\t\t\t    type : \"get\",\r\n");
      out.write("\t\t\t\t    dataType : \"json\",\r\n");
      out.write("\t\t\t\t\tdata : {loginid : loginid, profileid : profileid, profilerole : \"H\"},\t\t\r\n");
      out.write("\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.result == '1' ) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"호스트에게 요청을 완료하였습니다.\");\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse if(data.result == '2'){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"서퍼를 등록하지 않아 요청할 수 없습니다.\");\r\n");
      out.write("\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\telse if(data.result == '0') {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이미 요청한 사용자입니다.\");\r\n");
      out.write("\t\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이미 매칭이 되어 있습니다.\");\r\n");
      out.write("\t\t\t\t\t\t}   \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction srequest() {\r\n");
      out.write("\t\tif(loginid == profileid) {\r\n");
      out.write("\t\t\talert(\"자신에게는 신청할 수 없습니다.\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tif(safety == 'N') {\r\n");
      out.write("\t\t\t\talert(\"안전 유의 사항을 체크해주세요.\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$.ajax({\t\r\n");
      out.write("\t\t\t\t  \turl : \"/hifive/request\",\r\n");
      out.write("\t\t\t\t    type : \"get\",\r\n");
      out.write("\t\t\t\t    dataType : \"json\",\r\n");
      out.write("\t\t\t\t\tdata : {loginid : loginid, profileid : profileid, profilerole : \"S\"},\t\t\r\n");
      out.write("\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.result == '1' ) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"서퍼에게 요청을 완료하였습니다.\");\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse if(data.result == '2'){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"호스트를 등록하지 않아 요청할 수 없습니다.\");\r\n");
      out.write("\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t\telse if(data.result == '0') {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이미 요청한 사용자입니다.\");\r\n");
      out.write("\t\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이미 매칭이 되어 있습니다.\");\r\n");
      out.write("\t\t\t\t\t\t}         \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction prequest() {\r\n");
      out.write("\t\tif(loginid == profileid) {\r\n");
      out.write("\t\t\talert(\"자신에게는 신청할 수 없습니다.\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tif(safety == 'N') {\r\n");
      out.write("\t\t\t\talert(\"안전 유의 사항을 체크해주세요.\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$.ajax({\t\r\n");
      out.write("\t\t\t\t  \turl : \"/hifive/request\",\r\n");
      out.write("\t\t\t\t    type : \"get\",\r\n");
      out.write("\t\t\t\t    dataType : \"json\",\r\n");
      out.write("\t\t\t\t\tdata : {loginid : loginid, profileid : profileid, profilerole : \"P\"},\t\t\r\n");
      out.write("\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data.result == '1' ) {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"파트너에게 요청을 완료하였습니다.\");\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse if(data.result == '2') {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"파트너를 등록하지 않아 요청할 수 없습니다.\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse if(data.result == '0') {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이미 요청한 목록에 있습니다.\");\r\n");
      out.write("\t\t\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이미 매칭이 되어 있습니다.\");\r\n");
      out.write("\t\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"hidden\" value=\"");
      out.print( loginuserid );
      out.write("\" id=\"loginuserid\">\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("\n");
 
   String userId = (String)session.getAttribute("userId");
   String userName = (String)session.getAttribute("userName");
   User headeruser = (User)session.getAttribute("loginuser");
   

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/hifive/resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/hifive/resources/image/index/logo2.png\" />\r\n");
      out.write("<title>Traveler's Couch</title>\r\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\theader {\r\n");
      out.write("\t\tmargin: 5px;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\twidth: 1000px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.manubar {\r\n");
      out.write("\t\twidth: 300px;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\tleft: 73%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.manunav {\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.messagelist {\r\n");
      out.write("\t\twidth: 45px;\r\n");
      out.write("\t\theight: 40px; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.profileimg {\r\n");
      out.write("\t\twidth: 45px;\r\n");
      out.write("\t\theight: 45px;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("\t.dropdownMenuLink:hover {\r\n");
      out.write("\t\ttext-shadow:2px 2px #ff0000;\r\n");
      out.write("\t} \t\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"/hifive/resources/js/jquery-3.3.1.min.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction callMyPage() {\r\n");
      out.write("\t\tvar userId = $(\"#userid\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"/hifive/info\",\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\tdata : {userid : userId},\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data){\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tlocation.href = \"/hifive/views/user/mypage.jsp\";\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t\t}); //ajax\r\n");
      out.write("\t} //callMyPage\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<input type=\"hidden\" id=\"userid\" name=\"userid\" value=");
      out.print( userId );
      out.write(">\r\n");
      out.write("\t<script src=\"/hifive/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("\t<script\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container1\">\r\n");
      out.write("\t\t<header>\r\n");
      out.write("\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t<a href=\"/hifive/main.jsp\"><img\r\n");
      out.write("\t\t\t\t\tsrc=\"/hifive/resources/image/logo.png\"\r\n");
      out.write("\t\t\t\t\tclass=\"rounded mx-auto d-block\" alt=\"로고\" title=\"메인 페이지로 이동\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"manubar\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<nav class=\"manunav\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>");
      out.print( userName );
      out.write("님 &nbsp;&nbsp;</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th><a href=\"/hifive/views/message/messageList.jsp\"> \r\n");
      out.write("\t\t\t\t\t\t\t<img id=\"msg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"/hifive/resources/image/micon.jpg\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"messagelist\" title=\"요청받은 목록\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>&nbsp;</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th><a href=\"/hifive/profileinfo?userid=");
      out.print( userId );
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t\t   <img class=\"profileimg rounded-circle\"\r\n");
      out.write("                  src=\"/hifive/resources/profileUpfiles/");
      out.print( headeruser.getProfile_image() );
      out.write("\" alt=\"프로필 사진\" title=\"프로필로 이동\">\r\n");
      out.write("                  \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a>&nbsp;</th>\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"dropdown\" id=\"support\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn dropdown-toggle p-3 mb-2 bg-white text-dark font-weight-bold\" href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\trole=\"button\" id=\"dropdownMenuLink\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\"> menu </a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/hifive/noticelist\">공지사항</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/hifive/info?userid=");
      out.print( userId );
      out.write("\" onclick=\"callMyPage();\">마이페이지</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/hifive/reportlist\">신고게시판</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/hifive/views/support/tutorial.jsp\">튜토리얼</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/hifive/views/support/safety.jsp\">안전유의사항</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"/hifive/logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      <hr>\r\n");
      out.write("      <div id=\"main\">\r\n");
      out.write("         <div id=\"menu\">\r\n");
      out.write("            <div class=\"card\" style=\"width: 250px;\">\r\n");
      out.write("               <font size=\"3\"><b>Profile</b></font> \r\n");
      out.write("                  \r\n");
      out.write("                   <img class=\"card-img-top rounded-circle\"\r\n");
      out.write("                  src=\"/hifive/resources/profileUpfiles/");
      out.print( user.getProfile_image() );
      out.write("\" alt=\"Card image cap\" height=\"250px\">\r\n");
      out.write("               \r\n");
      out.write("                  \r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <p class=\"card-text\">\r\n");
      out.write("                  <div id=\"userInfo\" name=\"userInfo\" align=\"center\">\r\n");
      out.write("                     <font size=\"4\"><b>");
      out.print( user.getUser_Name() );
      out.write("</b></font> <br>\r\n");
      out.write("                     \r\n");
      out.write("                     <a title=\"지도 보기\" class=\"mapopen\" style=\"border: 0; background: white;\"\r\n");
      out.write("                        data-toggle=\"modal\" data-target=\"#openMap\">\r\n");
      out.write("                        <img src=\"/hifive/resources/image/map.png\" width=\"27\"\r\n");
      out.write("                           height=\"27\">\r\n");
      out.write("                     </button>\r\n");
      out.write("                     <font size=\"2\"> \r\n");
      out.write("                     ");
 if(user.getAddress() == null) { 
      out.write("\r\n");
      out.write("                     \t주소를 입력하지 않았습니다.\r\n");
      out.write("                     ");
 } else { 
      out.write("\r\n");
      out.write("                     ");
      out.print( user.getAddress() );
      out.write("\r\n");
      out.write("                     ");
 } 
      out.write(" \r\n");
      out.write("                     </font>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <br> \r\n");
      out.write("                  <center>\r\n");
      out.write("                     ");
 if(user.getNationality() == null) { 
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("                     ");
 } else { 
      out.write("\r\n");
      out.write("                     <h4><b>");
      out.print( user.getNationality() );
      out.write("</b></h4>\r\n");
      out.write("                     ");
 } 
      out.write(" \r\n");
      out.write("\t\t\t\t\t</center>\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <div id=\"request\" name=\"request\" align=\"center\">\r\n");
      out.write("                     <table border=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                           <th>\r\n");
      out.write("                           ");
 if(loginuserid.equals(user.getUser_Id())) {} else{
      out.write("\r\n");
      out.write("                          ");
 if(profileH != null) { 
      out.write("\r\n");
      out.write("                          <input type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("                              value=\"Host에게 요청하기\" id=\"requestH\" style=\"width: 200px;\" onclick=\"hrequest();\">\r\n");
      out.write("                           ");
} else { 
      out.write(" \r\n");
      out.write("                            <input type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("                              value=\"Host에게 요청하기\" disabled id=\"requestH\" style=\"width: 200px;\">\r\n");
      out.write("\t\t\t\t\t\t   ");
 }} 
      out.write(" \r\n");
      out.write("                           </th>\r\n");
      out.write("                              \r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                           <th>\r\n");
      out.write("                           ");
 if(loginuserid.equals(user.getUser_Id())) {} else{
      out.write("\r\n");
      out.write("                           ");
 if(profileS != null) { 
      out.write("\r\n");
      out.write("                           <input type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("                              value=\"Surfer에게 요청하기\" id=\"requestS\" style=\"width: 200px;\" onclick=\"srequest();\">\r\n");
      out.write("                              ");
} else { 
      out.write(" \r\n");
      out.write("                              <input type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("                              value=\"Surfer에게 요청하기\" disabled id=\"requestS\" style=\"width: 200px;\">\r\n");
      out.write("                              ");
 }} 
      out.write("  \r\n");
      out.write("                              </th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                           <th>\r\n");
      out.write("                           ");
 if(loginuserid.equals(user.getUser_Id())) {} else{
      out.write("\r\n");
      out.write("                           ");
 if(profileP != null) { 
      out.write("\r\n");
      out.write("                           <input type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("                              value=\"Partner에게 요청하기\" id=\"requestP\" style=\"width: 200px;\" onclick=\"prequest();\">\r\n");
      out.write("                               ");
} else { 
      out.write(" \r\n");
      out.write("                               <input type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("                              value=\"Partner에게 요청하기\" disabled id=\"requestS\" style=\"width: 200px;\">\r\n");
      out.write("                               ");
 }} 
      out.write(" \r\n");
      out.write("                              </th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                     </table>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <br> <br>\r\n");
      out.write("                  <div id=\"favorite\" name=\"favorite\" align=\"center\">\r\n");
      out.write("                     \r\n");
      out.write("                  </div>\r\n");
      out.write("                  </p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"content1\">\r\n");
      out.write("            <div class=\"card\" id=\"basisinfo\" style=\"width: auto;\">\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                   <ul>\r\n");
      out.write("                     <li>\r\n");
      out.write("                       <div class=\"form-group row\">\r\n");
      out.write("                       <label class=\"col-sm-2 col-form-label\">Gender</label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                           <input type=\"text\" style=\"background-color: #ffffff; text-align:center;\" disabled class=\"form-control col-sm-3\" name=\"gender\" \r\n");
      out.write("                           \t\t");
 if(user.getGender().equals("F")){ 
      out.write("\r\n");
      out.write("                           \t\t\tvalue=\"여성\"\r\n");
      out.write("                           \t\t");
 }else{ 
      out.write("\r\n");
      out.write("                           \t\t    value=\"남성\"      \t\t\t\r\n");
      out.write("                           \t\t");
 } 
      out.write(">\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>   \r\n");
      out.write("                     </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div class=\"form-group row\">\r\n");
      out.write("                        <label class=\"col-sm-2 col-form-label\">Birth</label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                           <input type=\"text\" style=\"background-color: #ffffff; text-align:center;\" disabled class=\"form-control col-sm-3\" name=\"birth\" value=\"");
      out.print( user.getBirth() );
      out.write("\">\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>   \r\n");
      out.write("                     </li>                             \r\n");
      out.write("                     <li>\r\n");
      out.write("                        <div class=\"form-group row\">\r\n");
      out.write("                        <label class=\"col-sm-2 col-form-label\">Job</label>\r\n");
      out.write("                           <div class=\"col-sm-10\">\r\n");
      out.write("                           <input type=\"text\" style=\"background-color: #ffffff; text-align:center;\" disabled class=\"form-control col-sm-3\" name=\"job\"          \r\n");
      out.write("                           ");
 if(user.getJob() == null){ 
      out.write("\r\n");
      out.write("                           \t\t\tvalue=\"\"\r\n");
      out.write("                           ");
 }else{ 
      out.write("\r\n");
      out.write("                           \t\t    value= ");
      out.print( user.getJob() );
      out.write("     \t\t\t\r\n");
      out.write("                           ");
 } 
      out.write(">      \r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li> \r\n");
      out.write("                    <li>\r\n");
      out.write("                     \t<div class=\"form-group row\">\r\n");
      out.write("                        <label class=\"col-sm-2 col-form-label\">Hobby</label>\r\n");
      out.write("                           <div class=\"col-sm-10\">          \r\n");
      out.write("                           ");
 if(user.getHobby() == null){ 
      out.write("\r\n");
      out.write("                    \t\t    선택된 취미가 없습니다.\r\n");
      out.write("                    \t   ");
 } else { 
                    		   String[] hobbies = user.getHobby().split(","); 
      out.write("\r\n");
      out.write("                    \t\t   ");
 for(String s : hobbies) { 
      out.write("\r\n");
      out.write("                    \t\t   \t\t<input type=\"button\" disabled class=\"btn btn-outline-dark\" name=\"hobby\"\r\n");
      out.write("                    \t\t   \t\tvalue=\"");
      out.print( s );
      out.write("\">                    \t\t   \t\t\r\n");
      out.write("                    \t\t   ");
 } 
      out.write("\r\n");
      out.write("\t\t               \t   ");
 } 
      out.write("\r\n");
      out.write("              \r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>    \r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div id=\"intro\" class=\"card\" style=\"width: auto;\">\r\n");
      out.write("               <h6 class=\"card-header\" id=\"card_info\">Introduction</h6>\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <p class=\"card-text\">\r\n");
      out.write("                    ");
 if(user.getContent() == null) {
      out.write("\r\n");
      out.write("                  \t<center>입력된 내용이 없습니다.</center>\r\n");
      out.write("                  \t");
} else {
      out.write("\r\n");
      out.write("                  \t");
      out.print( user.getContent() );
      out.write("\r\n");
      out.write("                  \t");
} 
      out.write("\r\n");
      out.write("                  </p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div id=\"infomenu\" style=\"margin-left: 8px;\">\r\n");
      out.write("                  <center>\r\n");
      out.write("                  <a href=\"#myhome\"><input type=\"button\" class=\"btn btn-outline-info\" value=\"My Home\" style=\"width: 130px;\"></a>&nbsp;&nbsp;\r\n");
      out.write("                  <a href=\"#surfer\"><input type=\"button\" class=\"btn btn-outline-info\" value=\"Surfer\" style=\"width: 130px;\"></a>&nbsp;&nbsp;\r\n");
      out.write("                  <a href=\"#partner\"><input type=\"button\" class=\"btn btn-outline-info\" value=\"Partner\" style=\"width: 130px;\"></a>&nbsp;&nbsp;\r\n");
      out.write("                  <a href=\"#photo\"><input type=\"button\" class=\"btn btn-outline-info\" value=\"Photos\" style=\"width: 130px;\"></a>&nbsp;&nbsp;\r\n");
      out.write("                  <a href=\"#reference\"><input type=\"button\" class=\"btn btn-outline-info\" value=\"References\" style=\"width: 130px;\"></a>\r\n");
      out.write("                  </center>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            \r\n");
      out.write("           <div id=\"myhome\" class=\"card\" style=\"width: auto;\">\r\n");
      out.write("               <h6 class=\"card-header\" id=\"card_info\">My Home</h6>\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <p class=\"card-text\">\r\n");
      out.write("                  ");
 if(profileH == null) { 
      out.write("\r\n");
      out.write("                  \t\t<center>등록된 호스트 정보가 없습니다.</center>\r\n");
      out.write("                  ");
} else { 
      out.write("\r\n");
      out.write("                  <ul>\r\n");
      out.write("                  <table cellpadding=\"10px\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td width=\"150px\"><li>최대 가능 인원</li></td>\r\n");
      out.write("                        <td width=\"500px\"><input type=\"text\" class=\"form-control col-sm-3\" disabled style=\"background-color: #ffffff; text-align:center;\" value=\"");
      out.print( profileH.getUser_num() );
      out.write("\"></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td><li>선호하는 성별</li></td>\r\n");
      out.write("                         <td>\r\n");
      out.write("                         \r\n");
      out.write("                           <input type=\"text\" class=\"form-control col-sm-3\" name=\"gender\" disabled style=\"background-color: #ffffff; text-align:center;\" \r\n");
      out.write("                           ");
 if(profileH.getP_gender().equals("B")) { 
      out.write("\r\n");
      out.write("                           value=\"상관 없음\"\r\n");
      out.write("                           ");
 } else if(profileH.getP_gender().equals("F")) { 
      out.write("\r\n");
      out.write("                           value=\"여성\"\r\n");
      out.write("                           ");
 } else { 
      out.write("\r\n");
      out.write("                           value=\"남성\"\r\n");
      out.write("                           ");
 } 
      out.write(" >\r\n");
      out.write("                        </td> \r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                       <td><li>기타가능여부</li></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                        <table>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                         ");
 if(profileH.getCheck1() == null){ 
      out.write("\r\n");
      out.write("                    \t\t  아이, 애완동물, 흡연, 음주 모두 가능하지 않습니다.\r\n");
      out.write("                    \t   ");
 } else { 
                    		   String[] possible = profileH.getCheck1().split(","); 
      out.write("\r\n");
      out.write("                    \t\t   ");
 for(String s : possible) { 
      out.write("\r\n");
      out.write("                    \t\t   <td>\r\n");
      out.write("\t                               <input class=\"btn btn-outline-secondary btn-sm\" id=\"smoking\" type=\"button\" name=\"hostcheck\" value=\"");
      out.print( s );
      out.write("\">\r\n");
      out.write("\t                           </td>\r\n");
      out.write("                    \t\t   ");
 } 
      out.write("\r\n");
      out.write("\t\t               \t   ");
 } 
      out.write("\r\n");
      out.write("\t\t               \t   </tr>\r\n");
      out.write("                           </table>                  \r\n");
      out.write("                        </td>\r\n");
      out.write("                     </tr>            \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td><li>수면 장소 </li></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           <input type=\"text\" class=\"form-control col-sm-3\" disabled name=\"sleeping\" style=\"background-color: #ffffff; text-align:center;\" value=\"");
      out.print( profileH.getCheck2() );
      out.write("\">                               \r\n");
      out.write("                        </td>\r\n");
      out.write("                     </tr>     \r\n");
      out.write("                     <tr>\r\n");
      out.write("                     \t<td><li>주소</li></td>\r\n");
      out.write("                     \t<td><textarea class=\"form-control\" id=\"hostcity\" name=\"city\" rows=\"1\" cols=\"60\" disabled style=\"text-align:left; background-color: #ffffff;\">");
      out.print( profileH.getCity() );
      out.write("</textarea></td>\r\n");
      out.write("                     </tr>          \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td><li>추가 정보</li></td>\n");
      out.write("                        <td><textarea class=\"form-control\" id=\"hostcontent\" name=\"etc\" rows=\"3\" cols=\"60\" disabled style=\"text-align:left; background-color: #ffffff;\">");
 if(profileH.getContent() == null) { 
      out.write("추가 정보를 입력하지 않았습니다.");
 } else { 
      out.print( profileH.getContent() );
 } 
      out.write("</textarea></td>   \n");
      out.write("                     </tr>\r\n");
      out.write("                  </table> \r\n");
      out.write("                  </ul>\r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  </p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div id=\"photo\" class=\"card\" style=\"width: auto;\">\r\n");
      out.write("               <h6 class=\"card-header\" id=\"card_info\">Photos</h6>\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("               ");
 if(profileH != null) { 
      out.write("\r\n");
      out.write("\t               ");
 if(profileH.getImage1() == null && profileH.getImage2() == null && profileH.getImage3() == null) { 
      out.write("\r\n");
      out.write("\t              \t<center>사진을 등록하지 않았습니다.</center> \r\n");
      out.write("\t               ");
 } else {
      out.write("\r\n");
      out.write("\t               ");
if(!profileH.getImage1().equals("sample.jpg") && profileH.getImage1() != null) { 
      out.write("\r\n");
      out.write("\t                  <img src=\"/hifive/resources/photoUpload/");
      out.print( profileH.getImage1() );
      out.write("\" class=\"rounded\" data-toggle=\"modal\"\r\n");
      out.write("\t                     data-target=\"#photoDetail\" style=\"width: 225px;\">\r\n");
      out.write("\t               ");
 } 
      out.write("\r\n");
      out.write("\t               ");
 if(!profileH.getImage2().equals("sample.jpg") && profileH.getImage2() != null) { 
      out.write(" \r\n");
      out.write("\t                  <img src=\"/hifive/resources/photoUpload/");
      out.print( profileH.getImage2() );
      out.write("\"  class=\"rounded\" data-toggle=\"modal\"\r\n");
      out.write("\t                     data-target=\"#photoDetail\" style=\"width: 225px;\">\r\n");
      out.write("\t               ");
 } 
      out.write("\r\n");
      out.write("\t               ");
 if(!profileH.getImage3().equals("sample.jpg") && profileH.getImage3() != null) { 
      out.write(" \r\n");
      out.write("\t                  <img src=\"/hifive/resources/photoUpload/");
      out.print( profileH.getImage3() );
      out.write("\"  class=\"rounded\" data-toggle=\"modal\"\r\n");
      out.write("\t                     data-target=\"#photoDetail\" style=\"width: 225px;\">\r\n");
      out.write("\t               ");
 } 
      out.write(" \r\n");
      out.write("\t               ");
 } 
      out.write("             \r\n");
      out.write("               ");
 } else { 
      out.write("\r\n");
      out.write("              \t <center>등록된 호스트 정보가 없습니다.</center>\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("               </div>               \r\n");
      out.write("               </div>\r\n");
      out.write("               <br>\r\n");
      out.write("            <div id=\"surfer\" class=\"card\" style=\"width: auto;\">\r\n");
      out.write("               <h6 class=\"card-header\" id=\"card_info\">Surfer</h6>\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <p class=\"card-text\">\r\n");
      out.write("                  ");
 if(profileS == null) { 
      out.write("\r\n");
      out.write("                  \t\t<center>등록된 서퍼 일정이 없습니다.</center>\r\n");
      out.write("                  ");
} else { 
      out.write("\r\n");
      out.write("                   <ul>\r\n");
      out.write("                     <table cellpadding=\"10px\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td width=\"150px\"><li>목적지</li></td>\r\n");
      out.write("                        <td width=\"500px\"><input type=\"text\" value=\"");
      out.print( profileS.getCity() );
      out.write("\" class=\"form-control col-sm-7\" name=\"city\" id=\"s-destination\" disabled style=\"background-color: #ffffff;S\">\r\n");
      out.write("                     </tr>                     \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        \r\n");
      out.write("                        <td><li><label>여행기간</label></li></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                        <div class=\"form-row\">  \r\n");
      out.write("                           &nbsp;\r\n");
      out.write("                           <input type=\"text\" value=\"");
      out.print( profileS.getStart_date() );
      out.write("\" class=\"form-control col-sm-3\" id=\"s-startdate\" disabled style=\"background-color: #ffffff; text-align:center;\" name=\"s-startdate\">&nbsp;&nbsp; ~ &nbsp;&nbsp;\r\n");
      out.write("                           <input type=\"text\" value=\"");
      out.print( profileS.getEnd_date() );
      out.write("\" class=\"form-control col-sm-3\" id=\"s-enddate\" disabled style=\"background-color: #ffffff; text-align:center;\" name=\"s-enddate\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                       \r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td><li>인원</li></td>\r\n");
      out.write("                        <td><input type=\"text\" id=\"s-num\" value=\"");
      out.print( profileS.getUser_num() );
      out.write("\" class=\"form-control col-sm-3\" name=\"s-num\" disabled style=\"background-color: #ffffff; text-align:center;\"></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  </ul> \r\n");
      out.write("                  ");
 } 
      out.write("            \r\n");
      out.write("                  </p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div id=\"partner\" class=\"card\" style=\"width: auto;\">\r\n");
      out.write("               <h6 class=\"card-header\" id=\"card_info\">Partner</h6>\r\n");
      out.write("               <div class=\"card-body\">\r\n");
      out.write("                  <p class=\"card-text\">\r\n");
      out.write("                  ");
 if(profileP == null) { 
      out.write("\r\n");
      out.write("                  \t\t<center>등록된 파트너 일정이 없습니다.</center>\r\n");
      out.write("                  ");
} else { 
      out.write(" \r\n");
      out.write("                  <ul>\r\n");
      out.write("                     <table cellpadding=\"10px\">\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td width=\"150px\"><li>목적지</li></td>\r\n");
      out.write("                        <td width=\"500px\"><input type=\"text\" value=\"");
      out.print( profileP.getCity() );
      out.write("\" class=\"form-control col-sm-7\" name=\"city\" id=\"p-destination\" disabled style=\"background-color: #ffffff;\"></textarea>\r\n");
      out.write("                     </tr>                     \r\n");
      out.write("                     <tr>\r\n");
      out.write("                        \r\n");
      out.write("                        <td><li><label>여행기간</label></li></td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                        <div class=\"form-row\">  \r\n");
      out.write("                           &nbsp;\r\n");
      out.write("                           <input type=\"text\" class=\"form-control col-sm-3\" value=\"");
      out.print( profileP.getStart_date() );
      out.write("\" id=\"p-startdate\" disabled style=\"background-color: #ffffff; text-align:center;\" name=\"p-startdate\">&nbsp;&nbsp; ~ &nbsp;&nbsp;\r\n");
      out.write("                           <input type=\"text\" class=\"form-control col-sm-3\" value=\"");
      out.print( profileP.getEnd_date() );
      out.write("\" id=\"p-enddate\" disabled style=\"background-color: #ffffff; text-align:center;\" name=\"p-enddate\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                       \r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td><li>인원</li></td>\r\n");
      out.write("                        <td><input type=\"text\" id=\"p-num\" value=\"");
      out.print( profileP.getUser_num() );
      out.write("\" class=\"form-control col-sm-3\" name=\"p-num\" disabled style=\"background-color: #ffffff; text-align:center;\"></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                  </ul> \r\n");
      out.write("                  ");
 } 
      out.write("\r\n");
      out.write("                  </p>\r\n");
      out.write("               </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            \r\n");
      out.write("        \r\n");
      out.write("   \r\n");
      out.write("            <div id=\"reference\" class=\"card\" style=\"width: auto; height: 200px\">\r\n");
      out.write("               <h6 class=\"card-header\" id=\"card_info\">References</h6>\r\n");
      out.write("               <div class=\"card-body\" id=\"review\" align='center' style=\"overflow-y:auto\">\r\n");
      out.write("                  \r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"review_write\"></div>\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("      <br>\r\n");
      out.write("      <hr>\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/hifive/resources/css/bootstrap.min.css\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title></title>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("      \r\n");
      out.write("      footer {\r\n");
      out.write("          margin: 20px;\r\n");
      out.write("          padding: 10px;\r\n");
      out.write("           width: 1000px;\r\n");
      out.write("         height : 70px;      \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("     /*  #language {\r\n");
      out.write("         display : inline-block;\r\n");
      out.write("         left : 60%;\r\n");
      out.write("      }  */\r\n");
      out.write("   </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/hifive/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t2018- Copyright Hi-Five Inc. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t<button class=\"btn btn-secondary\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\tdata-target=\"#accessTerms\" id=\"kk\">이용약관</button>&nbsp;&nbsp;\r\n");
      out.write("\t\t<button class=\"btn btn-secondary\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\tdata-target=\"#policy\" id=\"kk\">정책</button>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- <div class=\"dropdown\" id=\"language\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button class=\"btn btn-secondary btn-sm dropdown-toggle\"\r\n");
      out.write("\t\t\t\ttype=\"button\" id=\"dropdownMenuButton\" data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\taria-haspopup=\"true\" aria-expanded=\"false\">LANGUAGE</button>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">KOREAN</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">ENGLISH</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> -->\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 이용약관 Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"accessTerms\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalLongTitle\">\r\n");
      out.write("\t\t\t\t\t\t<b>이용약관</b>\r\n");
      out.write("\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<font style = \"color:#ff6633; font-size: 15pt\">\r\n");
      out.write("<b>본 이용 약관을주의 깊게 읽으십시오.</b></font><br> <br>\r\n");
      out.write("<font style = \"color:black; font-size: 11pt\">\r\n");
      out.write("<b>계정 등록 또는 서비스 액세스 또는 사용으로 귀하는 본 사용 약관 및 참조로 작성된 모든 조건을 준수함에 동의하게됩니다.</b></font><br><br>\r\n");
      out.write("<b>이 약관에 동의하지 않을 경우 서비스를 이용하지 마십시오.</b> <br><br>\r\n");
      out.write("<font style = \"color:black; font-size: 10pt\">\r\n");
      out.write("Hifive International, Inc.의 웹 사이트, 기타 온라인 또는 서비스 (총칭하여 \"서비스\")에 대한 귀하의 액세스 및 사용 ( \"Traveler's Couch\", \" 우리 \"또는\"우리 \"). 귀하가 어떤 단체를 대신하여 서비스를 사용하는 경우, 귀하는 귀하가 해당 단체를 대신하여 본 약관에 동의 할 권한이 있음을 진술하고 보증하며, 해당 단체는 귀하가 본 약관을 위반하는 것에 대해 책임을집니다. 본 약관에 따라 서비스를 사용하지 않으면 서비스 사용에 대한 귀하의 권리가 해지 또는 정지 될 수 있으며 Traveler's Couch 및 / 또는 심각한 민법 및 / 또는 형사 처벌로 법적 조치를받을 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("우리는 언제든지 재량에 따라 본 약관 또는 서비스의 정책이나 지침을 변경하거나 수정할 권리가 있습니다. Traveler's Couch이 약관을 변경하는 경우,이 약관의 상단에 날짜를 수정하는 것을 포함하여 변경 통지를 제공합니다. 변경 또는 수정 사항을 게시 한 후에 서비스를 계속 사용하면 그러한 변경 또는 수정 사항을 수락하는 것으로 간주됩니다. 따라서 귀하는 서비스 사용에 적용되는 이용 약관을 이해하기 위해 본 약관 및 해당 정책 및 지침을 자주 검토해야합니다.\r\n");
      out.write("\r\n");
      out.write("Traveler's Couch이 회원에 관한 정보를 수집, 사용 및 공개하는 방법에 대한 정보는 개인 정보 보호 정책을 참조하십시오. 또한 서비스에 액세스하거나 사용함으로써 커뮤니티 지침을 준수하는 데 동의하게됩니다.\r\n");
      out.write("\r\n");
      out.write("이 약관과 관련하여 질문이 있으시면 연락주십시오. 이메일 trevelsfriend@gmail.com 으로 문의하실 수 있습니다.\r\n");
      out.write("</font>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 정책 Modal -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"policy\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("\t\taria-labelledby=\"exampleModalLongTitle\" aria-hidden=\"true\">\r\n");
      out.write("\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalLongTitle\">\r\n");
      out.write("\t\t\t\t\t\t<b>정책</b>\r\n");
      out.write("\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<font style = \"color:#ff6633; font-size: 15pt\">\r\n");
      out.write("<b>Traveler's Couch 정책</font><br><br>\r\n");
      out.write("<font style = \"color:#ff6633; font-size: 13pt\"><b>행동 정책</b></font><br><br>\r\n");
      out.write("<font style = \"color:black; font-size: 10pt\">\r\n");
      out.write("1. 스팸하지 마십시오 : 우리는 인간 상호 작용을 소중히 여기며 사이트의 콘텐츠를 원하고 구성원에게 개인화되고 가치있게 보내집니다.\r\n");
      out.write("동일한 메시지를 사이트, 회원 간 메시지, 소파 요청, 그룹, 지역 토론 또는 이벤트 목록에 복사하여 붙여 넣는 것은 허용되지 않습니다. \r\n");
      out.write("메시지 유형을 수신 할 의사가없는 많은 회원에게 보내는 메시지는 스팸으로 간주 될 수도 있습니다.\r\n");
      out.write("<br>\r\n");
      out.write("2. 날짜를 찾지 마라. 우리 멤버들은 Traveler's Couch에 가입하여 우정을 쌓는다.\r\n");
      out.write("데이트를 위해 다른 회원들에게 연락하지 마시고, 성 파트너를 찾으려면 다른 사이트를 이용하십시오.\r\n");
      out.write("Google은 온라인 및 오프라인에서 원치 않는 성적인 진보에 관한 보고서를 진지하게 받아들입니다.\r\n");
      out.write("이러한 진술은 Google의 행동 강령을 위반 한 것으로 간주 될 수 있습니다. \r\n");
      out.write("여기에는 비 호스팅 / 서핑 관련 문제 및 성적 암시 행동에 대해 다른 회원들과 연락하려는 체계적인 시도가 포함될 수 있습니다. \r\n");
      out.write("타인의 경계를 존중하십시오. 다른 Traveler's Couch가 불편 함을 느끼면 자신의 감정을 존중하고 한 발 뒤로 물러나십시오.\r\n");
      out.write("<br>\r\n");
      out.write("3. 귀하의 소파를 청구하지 마십시오 : 우리 지역 사회는 친절한 환대를 제공합니다. \r\n");
      out.write("귀하의 소파와 교환하기 위해 돈이나 노동력을 요구하거나 회원에게 유료 숙박 서비스를 추천하는 것은 허용되지 않습니다.\r\n");
      out.write("<br>\r\n");
      out.write("4. 협박, 스토킹 또는 괴롭힘 : 스토킹, 협박, 위협 및 다른 회원의 괴롭힘은 금지됩니다. \r\n");
      out.write("괴롭힘은 대상자에게 불리한 영향을 미칠 목적으로 보이는 공격 행동의 패턴으로 정의됩니다. \r\n");
      out.write("괴롭힘의 예로는 위협 만들기, 사람과 반복적으로 원하지 않는 접촉, 다른 사람의 개인 정보 게시 등이 있습니다. \r\n");
      out.write(" Traveler's Couch은 미래의 호스트, 서퍼 또는  Traveler's Couch 커뮤니티에 위협이 될 수 있다고 생각하는 프로필에 대해 조치를 취할 권리를 보유합니다 (위 참조).\r\n");
      out.write("<br>\r\n");
      out.write("5. 하나의 프로파일 만 작성 : 중복, 위조 및 농담 프로파일은 허용되지 않습니다. \r\n");
      out.write("처음으로 만드는 프로필은 나와 있어야하며 가질 수있는 유일한 프로필입니다. \r\n");
      out.write("우리의 신뢰 네트워크는 모든 사람이 자신의 명성을 지킬 것을 요구합니다.\r\n");
      out.write("<br>\r\n");
      out.write("6. 너 자신 있으 십시오 : 너 자신을 다른 사람으로 잘못 표시하는 것은 금지되어 있습니다. \r\n");
      out.write("여기에는 대리인, 대리인, 직원 또는  Traveler's Couch의 제휴사로서의 대리인이 포함됩니다.\r\n");
      out.write("<br>\r\n");
      out.write("7. 법을 준수하십시오 : 불법 활동에 관여하거나 장려하지 마십시오. 관련 법률이나 규정을 위반하지 마십시오.\r\n");
      out.write("<br>\r\n");
      out.write("8.  Traveler's Couch을 올바르게 사용하십시오 : 다른 멤버가 사이트를 완전히 즐기지 못하게하거나 사이트의 기능을 해칠 수있는 방식으로 \r\n");
      out.write("Traveler's Couch을 사용하는 것은 금지됩니다. 여기에는 과도한보고, 플래그 또는 다른 구성원의 블록을 유발하는 동작이 포함됩니다. \r\n");
      out.write("우리는  Traveler's Couch 회원들이 신고 한 통신에 대한 적극적인 홍보 활동을 금지하거나 다른  Traveler's Couch에 대한 경험을 해할 것이라고 믿습니다.\r\n");
      out.write("또한 사이트에 바이러스, 손상된 데이터 또는 기타 잠재적으로 유해한 코드가 포함 된 것을 게시하십시오.  \r\n");
      out.write("Traveler's Couch 시스템을 우회하거나 의도를 저해하는 방식으로 이러한 시스템을 사용하려고 시도하는 것은 금지됩니다.\r\n");
      out.write("<br>\r\n");
      out.write("9. 다른 사람들에게 당신의 믿음과 생활 방식 선택을 강요하지 마십시오. \r\n");
      out.write("카우치 서핑은 회원들의 다양성을 자랑스럽게 생각합니다. \r\n");
      out.write("우리의 플랫폼을 사용하여 귀하의 라이프 스타일이나 신념 체계에 동참하기 위해 다른 회원을 모집하는 것은 우리의 행동 강령을 위반하는 것일 수 있습니다. \r\n");
      out.write("귀하의 라이프 스타일 또는 신념 체계의 채택을 귀하의 소파 제공 조건으로 삼지 마십시오. \r\n");
      out.write("특정 주택 규칙이 기대되는 반면, 서퍼에게 부과 된 조건이 위험을 초래하거나 회원 경험을 해치거나  Traveler's Couch의 평판을 손상한다고 판단되면 우리는 요구 사항을 금지 할 권리가 있습니다.\r\n");
      out.write("</font>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- 주소 지도 Modal -->\r\n");
      out.write("   <div class=\"modal fade\" id=\"openMap\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("      aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("         <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("               <h5 class=\"modal-title\">\r\n");
      out.write("                  <b>지도 확인</b>\r\n");
      out.write("               </h5>\r\n");
      out.write("               <button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("                  aria-label=\"Close\">\r\n");
      out.write("                  <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("               </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("            ");
 if(user.getAddress() != null) { 
      out.write("\r\n");
      out.write("               <div id=\"map\" style=\"width: 470px; height: 400px;\"></div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("                       주소를 입력해주세요.\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   ");
 if(profileH != null) { 
      out.write("\r\n");
      out.write("   ");
 if(profileH.getImage1() != null || profileH.getImage2() != null || profileH.getImage3() != null) { 
      out.write("\r\n");
      out.write("   <div class=\"modal fade bd-example-modal-lg align-middle\" id=\"photoDetail\"\r\n");
      out.write("      tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("      aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog modal-lg modal-dialog-centered\" \" role=\"document\">\r\n");
      out.write("         <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("               <h5 class=\"modal-title\">\r\n");
      out.write("                  <b>사진 상세보기</b>\r\n");
      out.write("               </h5>\r\n");
      out.write("               <button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("                  aria-label=\"Close\">\r\n");
      out.write("                  <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("               </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("               <div id=\"carouselExampleControls\" class=\"carousel slide\"\r\n");
      out.write("                  data-ride=\"carousel\">\r\n");
      out.write("                  <div class=\"carousel-inner\">\r\n");
      out.write("                     ");
 if(!profileH.getImage1().equals("sample.jpg") && profileH.getImage1() != null) { 
      out.write("\r\n");
      out.write("                     <div id=\"mphoto1\" class=\"carousel-item active\">                     \r\n");
      out.write("                        <img class=\"d-block w-100 \"\r\n");
      out.write("                           src=\"/hifive/resources/photoUpload/");
      out.print( profileH.getImage1() );
      out.write("\">\r\n");
      out.write("                     </div>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     ");
 if(!profileH.getImage2().equals("sample.jpg") || profileH.getImage2() != null) { 
      out.write("\r\n");
      out.write("                     <div id=\"mphoto2\"  class=\"carousel-item\">\r\n");
      out.write("                        <img class=\"d-block w-100\"\r\n");
      out.write("                           src=\"/hifive/resources/photoUpload/");
      out.print( profileH.getImage2() );
      out.write("\">\r\n");
      out.write("                     </div>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                     ");
 if(!profileH.getImage3().equals("sample.jpg") && profileH.getImage3() != null) { 
      out.write("\r\n");
      out.write("                     <div id=\"mphoto3\" class=\"carousel-item\">\r\n");
      out.write("                        <img class=\"d-block w-100\"\r\n");
      out.write("                           src=\"/hifive/resources/photoUpload/");
      out.print( profileH.getImage3() );
      out.write("\">\r\n");
      out.write("                     </div>\r\n");
      out.write("                     ");
 } 
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <a class=\"carousel-control-prev\" href=\"#carouselExampleControls\"\r\n");
      out.write("                     role=\"button\" data-slide=\"prev\"> <span\r\n");
      out.write("                     class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("                     class=\"sr-only\">Previous</span>\r\n");
      out.write("                  </a> <a class=\"carousel-control-next\" href=\"#carouselExampleControls\"\r\n");
      out.write("                     role=\"button\" data-slide=\"next\"> <span\r\n");
      out.write("                     class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> <span\r\n");
      out.write("                     class=\"sr-only\">Next</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
 } 
      out.write("\r\n");
      out.write("   ");
 } 
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("      var map = new naver.maps.Map('map', {\r\n");
      out.write("    \t  minZoom : 9,\r\n");
      out.write("    \t  zoom : 10,\r\n");
      out.write("    \t  maxZoom : 11\r\n");
      out.write("      });\r\n");
      out.write("      var myaddress = '");
      out.print( user.getAddress() );
      out.write("'; // 도로명 주소나 지번 주소만 가능 (건물명 불가!!!!) 여기에 사용자 주소\r\n");
      out.write("      naver.maps.Service.geocode({\r\n");
      out.write("         address : myaddress\r\n");
      out.write("      }, function(status, response) {\r\n");
      out.write("         if (status !== naver.maps.Service.Status.OK) {\r\n");
      out.write("            \r\n");
      out.write("         }\r\n");
      out.write("         var result = response.result;\r\n");
      out.write("         // 검색 결과 갯수: result.total\r\n");
      out.write("         // 첫번째 결과 결과 주소: result.items[0].address\r\n");
      out.write("         // 첫번째 검색 결과 좌표: result.items[0].point.y, result.items[0].point.x\r\n");
      out.write("         var myaddr = new naver.maps.Point(result.items[0].point.x,\r\n");
      out.write("               result.items[0].point.y);\r\n");
      out.write("         map.setCenter(myaddr); // 검색된 좌표로 지도 이동\r\n");
      out.write("         \r\n");
      out.write("         var markerOptions = {\r\n");
      out.write("        \tposition : myaddr,\r\n");
      out.write("        \tmap : map,\r\n");
      out.write("        \ticon : {\r\n");
      out.write("        \t\turl : '/hifive/resources/image/marker.png',\r\n");
      out.write("        \t\tsize : new naver.maps.Size(350, 350),\r\n");
      out.write("        \t\torigin : new naver.maps.Point(0, 0),\r\n");
      out.write("        \t\tanchor : new naver.maps.Point(175, 175)\r\n");
      out.write("        \t}\r\n");
      out.write("         }\r\n");
      out.write("         var marker = new naver.maps.Marker(markerOptions);\r\n");
      out.write("         \r\n");
      out.write("         // 마커 표시\r\n");
      out.write("         /* var marker = new naver.maps.Marker({\r\n");
      out.write("            position : myaddr,\r\n");
      out.write("            map : map\r\n");
      out.write("         }); */\r\n");
      out.write("         // 마커 클릭 이벤트 처리\r\n");
      out.write("         naver.maps.Event.addListener(marker, \"click\", function(e) {\r\n");
      out.write("            if (infowindow.getMap()) {\r\n");
      out.write("               infowindow.close();\r\n");
      out.write("            } else {\r\n");
      out.write("               infowindow.open(map, marker);\r\n");
      out.write("            }\r\n");
      out.write("         });\r\n");
      out.write("         // 마크 클릭시 인포윈도우 오픈\r\n");
      out.write("         var infowindow = new naver.maps.InfoWindow({\r\n");
      out.write("            content : myaddress\r\n");
      out.write("         });\r\n");
      out.write("      });\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
